# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="quetzal"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git python tmux zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


#############################################################################
#                        User ZSH Configuration
#############################################################################

export LANG=en_US.UTF-8

setopt histignorealldups sharehistory
setopt noflowcontrol

# Use emacs keybindings even if our EDITOR is set to vi
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Paths
export PYTHONPATH=${PYTHONPATH}:~/research/scripts/py:~/research/scripts/besl:~/research/scripts/astroquery:~/research/scripts/photutils:~/research/scripts/radex/Radex/radexgrid:~/research/scripts/astrodendro:~/research/scripts/plfit:~/research/scripts/click:~/code/ARTIST/lib/python2.7/site-packages
export GOROOT=$HOME/code/go
export GOPATH=$HOME/code/gocode
export MPLCONFIGDIR=~/.config/matplotlib
export CFITSIO=/usr/include:/usr/lib/x86_64-linux-gnu/:/usr/lib:/usr/local/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/include:~/code/qhull/lib:~/code/ARTIST/lib
export IDL_PATH=/usr/local/exelis/idl82/bin:/usr/local/exelis/idl82/lib:~/research/scripts/idl:~/research/scripts/astron:~/research/scripts/starfinder:~/research/scripts/IDLAstro/pro:~/research/scripts/idl-coyote/:~/research/scripts/cmtotal
export RATRAN=/media/svobodb/scratch/infall_model/Ratran
export RATRANRUN=/media/svobodb/scratch/infall_model/Ratran/run
export ARTIST_ROOT=/home/svobodb/code/ARTIST
export PATH=$PATH:/opt/bin:~/code/bin:~/code/mygbtidl/gbtidl:~/code/montage/bin:~/.cabal/bin:~/code/casapy/bin:~/code/casapy:$GOROOT/bin:$GOPATH/bin:$RATRAN/bin:$ARTIST_ROOT/bin:~/scratch/lime:~/.cargo/bin

# fasd
eval "$(fasd --init auto)"

### Alias ###
REM_HOST=host
REM_USER=user
function rpush {
	scp $1 $REM_USER@$REM_HOST.as.arizona.edu:/home/$REM_USER/Downloads
}
function rpull {
	scp $REM_USER@$REM_HOST.as.arizona.edu:/home/$REM_USER/$1 .
}
function rwget {
	ssh -t $REM_USER@$REM_HOST.as.arizona.edu "wget -P /home/'$REM_USER'/Downloads/ '$1'"
}
# neovim
alias nv='nvim'
# radio
alias groove="mplayer http://ice.somafm.com/groovesalad"
# fasd
alias v='f -e vim'
alias m='f -e mplayer'
alias o='a -e xdg-open'
# ls
alias ls='ls -F --color'
alias ll='ls -lF --color'
alias la='ls -aF --color'
function dls {
	echo `ls -l | grep "^d" | awk '{print $9}' | tr -d "/"`
}
# python
alias ipy='ipython'
alias ipy3='ipython3 --profile=three'
alias ipnb='ipython notebook'
# julia
alias jl='julia'
alias ijl='ipython console --profile julia'
alias ijnb='ipython notebook --profile julia'
# config
alias zshrc="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias vimrc="vim ~/.vimrc"
# misc
alias cad='cal;date'
alias dr='cd "$(< /tmp/cwd)"'
alias ds='pwd > /tmp/cwd'
alias grep='grep -n --color'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias tmux='tmux -2'
alias vw='vim -c VimwikiIndex'
alias slurm='slurm -i eth0'
alias trash='gvfs-trash'
alias hangups='hangups --col-scheme solarized-dark'
