# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="quetzal"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git python tmux zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


#############################################################################
#                        User ZSH Configuration
#############################################################################

# You may need to manually set your language environment
export LANG=en_US.UTF-8

setopt histignorealldups sharehistory
setopt noflowcontrol

# Use emacs keybindings even if our EDITOR is set to vi
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Paths
export PYTHONPATH=${PYTHONPATH}:~/research/scripts/py:~/research/scripts/besl:~/research/scripts/astroquery:~/research/scripts/photutils:~/research/scripts/radex/Radex/radexgrid:~/research/scripts/astrodendro:~/research/scripts/plfit:~/research/scripts/click
export MPLCONFIGDIR=~/.config/matplotlib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/multinest/lib
export PATH=$PATH:/opt/bin:~/code/bin:~/code/mygbtidl/gbtidl:~/code/montage/bin:~/.cabal/bin

# fasd
eval "$(fasd --init auto)"

### Alias ###
function rpush {
	scp $1 svobodb@rasalas.as.arizona.edu:/home/svobodb/Downloads
}
function rpull {
	scp svobodb@rasalas.as.arizona.edu:/home/svobodb/$1 .
}
function rwget {
	ssh -t svobodb@rasalas.as.arizona.edu "wget -P /home/svobodb/Downloads/ '$1'"
}
# radio
alias groove="mplayer http://ice.somafm.com/groovesalad"
# ssh
alias eldfs='sshfs svobodb@eldora.as.arizona.edu:/data0/svobodb/ /mnt/eld_data/ -C -o reconnect,auto_cache,workaround=all'
alias eldfs_off='fusermount -u /mnt/eld_data'
alias eldfs_home='sshfs svobodb@eldora.as.arizona.edu:/home/svobodb/ /mnt/eld_home/'
alias eldfs_home_off='fusermount -u /mnt/eld_home'
alias rasfs='sshfs svobodb@rasalas.as.arizona.edu:/home/svobodb/ /mnt/ras_data/ -C -o reconnect,auto_cache,workaround=all'
alias rasfs_off='fusermount -u /mnt/ras_data'
alias eldora="ssh -XC4 svobodb@eldora.as.arizona.edu"
alias greenbank="ssh -XC4 bsvoboda@ssh.gb.nrao.edu"
alias hht="ssh -XC4 obs@smtoast.as.arizona.edu"
alias rasalas="ssh -XC4 svobodb@rasalas.as.arizona.edu"
# fasd
alias v='f -e vim'
alias m='f -e mplayer'
alias o='a -e xdg-open'
# ls
alias ls='ls -F --color'
alias ll='ls -lF --color'
alias la='ls -aF --color'
function dls {
	echo `ls -l | grep "^d" | awk '{print $9}' | tr -d "/"`
}
# python
alias ipy='ipython console'
alias pylab='ipython console --pylab'
alias ipnb='ipython notebook --pylab inline'
# julia
alias jl='julia'
alias ijl='ipython console --profile julia'
alias ijnb='ipython notebook --profile julia'
# config
alias zshrc="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias vimrc="vim ~/.vimrc"
# misc
alias cad='cal;date'
alias dr='cd "$(< /tmp/cwd)"'
alias ds='pwd > /tmp/cwd'
alias grep='grep -n --color'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias tmux='tmux -2'
alias vn='vi notes.txt'
alias slurm='slurm -i eth0'
alias trash='gvfs-trash'
