# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load from ~/.oh-my-zsh/themes/ .
ZSH_THEME="quetzal"

# Enable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"
export UPDATE_ZSH_DAYS=13

DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git python tmux zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


#############################################################################
#                        User ZSH Configuration
#############################################################################

export LANG=en_US.UTF-8

setopt histignorealldups sharehistory
setopt noflowcontrol

# Use emacs keybindings even if our EDITOR is set to vi
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Paths
export MPLCONFIGDIR=~/.config/matplotlib
export PATH=/opt/bin:~/code/bin:~/code/anaconda3/bin:$PATH

# fasd -- https://github.com/clvv/fasd
eval "$(fasd --init auto)"

# fzf -- https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### Alias ###
# radio
alias groove="mplayer http://ice.somafm.com/groovesalad"
# fasd
alias v='f -e vim'
alias m='f -e mplayer'
alias o='a -e xdg-open'
# ls
alias ls='ls -F --color'
alias ll='ls -lF --color'
alias la='ls -aF --color'
function dls {
	echo $(ls -l | grep "^d" | awk '{print $9}' | tr -d "/")
}
# python
alias ipy='ipython'
alias ipy3='ipython3 --profile=three'
alias ipnb='ipython notebook'
# julia
alias jl='julia --banner=no --threads auto'
# config
alias zshrc="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias vimrc="vim ~/.vimrc"
# misc
alias cad='cal;date'
alias dr='cd "$(< /tmp/cwd)"'
alias ds='pwd > /tmp/cwd'
alias grep='grep -n --color'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias tmux='tmux -2'
alias vn='vi notes.txt'
alias slurm='slurm -i eth0'
alias trash='gvfs-trash'

source /home/brian/.config/broot/launcher/bash/br

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/brian/code/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/brian/code/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/brian/code/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/brian/code/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


